### PR TITLE
Upgrade ESLint to 2.8.0

### LINKED ISSUE #18: support eslint 2.0.0
A new version of eslint was released http://eslint.org/blog/2016/02/eslint-v2.0.0-released

As this hound service is still in beta, maybe is a good timing to move to eslint `2.0.0`

### PR DESCRIPTION
**Pull request by gylaz**
* Plugin management methods have been renamed slightly upstream.
* Update the Airbnb config fixture, because Airbnb's config has evolved.

Closes #18

### CODE REVIEW

**Comment by teoljungberg** [comment]
I see nothing obviously wrong with it, it might be worth trying it out on staging.

**Comment by gylaz** [comment]
Hound keeps getting stuck on this. No errors that I can see on our end.

**Comment by gylaz** [comment]
Had to disable JSHint/JSCS in b1a7572ef9b5079100e011dec9ac65b46c60ae49 to make Hound happy. (JSCS has to go).

**Comment by jiajiawang** [comment]
Any plans to merge this PR into master?

**Comment by timaschew** [comment]
Are there any issues? 
Is there something to help out?

**Pull request merged**
